name: Continuous Deployment to OVH (Dev)

on:
  push:
    branches: [develop]
    
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: repo name
        run: echo ${{ github.event.repository.name }}
        
      - name: ssh
        run: sshpass -p ${{ secrets.OVH_SSH_DEV_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.OVH_SSH_DEV_USER }}@${{ secrets.OVH_SSH_HOST }} -p ${{ secrets.OVH_SSH_PORT }} "rm -rv * && git clone --branch develop https://github.com/${{ github.event.actor.login }}/${{ github.event.repository.name }}.git && mv ${{ github.event.repository.name }}/* . && rm -rf ${{ github.event.repository.name }} && rm README.md"
