name: Github Actions [test]

on:
  push:
    branches: [develop]
    
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: check repo
        run: ls -lrt $GITHUB_WORKSPACE
        
      - name: ssh
        run: |
          sudo apt install sshpass
          sshpass -p ${{ secrets.OVH_SSH_PASSWORD }} ssh -tt ${{ secrets.OVH_SSH_USER }}@${{ secrets.OVH_SSH_HOST }} -p ${{ secrets.OVH_SSH_PORT }}
