name: Github Actions [test]

on:
  push:
    branches: [develop]
    
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: check repo
        run: ls -lrt $GITHUB_WORKSPACE
        
      - name: secrets ?
        run: echo ${{ secrets.AZURE_CREDENTIALS }}
